### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Berxz** [Ensidiya/trio#2]
Alpha.cpp
  Backtrack.cpp
  BulletTracer.cpp
  Chams.cpp
  EnginePrediction.cpp
  GrenadeRange.cpp
  Hitmarker.cpp
  Logs.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Alpha.cpp)
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Legit\Backtrack.cpp)
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\Chams.cpp)
  Nightmode.cpp
  SoundESP.cpp
  Thirdperson.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\SoundESP.cpp)
  GUI.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\GUI\GUI.cpp)
  Hooks.cpp
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\Logs.cpp)
  DLLMain.cpp
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\GrenadeRange.cpp)
  Triggerbot.cpp
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\Hitmarker.cpp)
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\EnginePrediction.cpp)
  Menu.cpp
  Zeusbot.cpp
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\BulletTracer.cpp)
  Settings.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\Nightmode.cpp)
  D3DFont.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\Thirdperson.cpp)
  DrawManager.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Hooks.cpp)
  GlobalVars.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Utils\D3DFont.cpp)
  Interfaces.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\DLLMain.cpp)
  NetvarManager.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Menu.cpp)
  ESP.cpp
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Utils\DrawManager.cpp)
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Features\ESP.cpp)
c:\users\berxzz\desktop\trio\antario\utils\d3dfont.h(3): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Settings.cpp)
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Legit\Triggerbot.cpp)
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Rage\Zeusbot.cpp)
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Utils\Interfaces.cpp)
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Utils\GlobalVars.cpp)
c:\users\berxzz\desktop\trio\antario\utils\netvarmanager.h(34): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Antario\Utils\NetvarManager.cpp)

**Comment by Ensidiya** [comment]
https://stackoverflow.com/questions/4931151/cannot-open-include-file-d3dx9-h

please google next time, i dont care about this source anymore.
